Fix bug where exception crashes program
Exception causes crash:

Snippet from stack trace:
```
  File "/yterm/yTermPlayer/yTermPlayer/music_api.py", line 258, in get_time_details
    minutes = int(total_seconds / 60)
UnboundLocalError: local variable 'total_seconds' referenced before assignment
```